services:
  - type: web
    name: srmu-otp
    env: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: WEBHOOK_URL
        sync: false
